language: go
sudo: false
go:
  - 1.10.x
before_install:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/contained.af-darwin-amd64
          - cross/contained.af-darwin-amd64.md5
          - cross/contained.af-darwin-amd64.sha256
          - cross/contained.af-darwin-386
          - cross/contained.af-darwin-386.md5
          - cross/contained.af-darwin-386.sha256
          - cross/contained.af-freebsd-amd64
          - cross/contained.af-freebsd-amd64.md5
          - cross/contained.af-freebsd-amd64.sha256
          - cross/contained.af-freebsd-386
          - cross/contained.af-freebsd-386.md5
          - cross/contained.af-freebsd-386.sha256
          - cross/contained.af-linux-arm
          - cross/contained.af-linux-arm.md5
          - cross/contained.af-linux-arm.sha256
          - cross/contained.af-linux-arm64
          - cross/contained.af-linux-arm64.md5
          - cross/contained.af-linux-arm64.sha256
          - cross/contained.af-linux-amd64
          - cross/contained.af-linux-amd64.md5
          - cross/contained.af-linux-amd64.sha256
          - cross/contained.af-linux-386
          - cross/contained.af-linux-386.md5
          - cross/contained.af-linux-386.sha256
          - cross/contained.af-windows-amd64
          - cross/contained.af-windows-amd64.md5
          - cross/contained.af-windows-amd64.sha256
          - cross/contained.af-windows-386
          - cross/contained.af-windows-386.md5
          - cross/contained.af-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "UgvN6AVvuIUHBwTQqS1m7Dn0e0yHQSQYFlZUrjbuRCc+cVNwF2K7mHwh3xaYcF/eyHc8MtHL91DTF1D9XhdR2XjyQbFtYOHxcG4ToTvpku4V9JF6JQg0SfDs2A5frHuV3dUKQXzZpusY36AkQ3ES3CFErwQBGAbScJSjKMsyBBPkI1jdpZhChiUJxi36NE6CZiiq6ij76Ho4cFlMlAOWCCcncprvULFMD9g6C4jEKyclwlcYCjCvOKpmtZMlJfMjKYw6gsKyuyRWeKSIa1goHlXdcgStW02kkBZVowJkig0UhThSf1fh8aFLovR1VaoiDzg+RsmaZc+3QpDV0KCyiW/uKAJ5CeNBy4lubnWJQmkKP1pmLv2LmqQ5Au4TazG7lMhK26eLu/vx2VL52k5aO30FZE7sbb9zbd2LtsuJWjZvLxm3pA6iLTF1qoS3To/Wq4VZiRsvx8bkZ3YbvNIA2IpiilN2OWi7XIz5ZaKW4MEUrj7mzKB1lIgTczz+JbiYxnu2uNCSRfrjCVLYiARI+K/Qa0ckiSqGq8pEpbxPujUS06IK1vghv1iO1nQl6VEqvMmLkNjZZAWgiuJ9oJ4qref86w55uddqeMzfK0LDrlR5OuAa6lgrOaRWFGlBvKJY0Z1B6/tg2sMOYlWkH5bvJMgD741zyBWJ6WlbENSIh0Q="
